sudo: required
services:
  - docker

scripts:
  - docker build -t cmoranp/node .
  - docker images cmoranp/node

before_deploy:
  - docker login -u cmoranp -p J$abina79

deploy:
  provider: script
  script: docker push cmoranp/node
  on:
    branch: master
    

